{
  "id": "CVE-2020-36810",
  "sourceIdentifier": "416baaa9-dc9f-4396-8d5f-8c081fb06d67",
  "published": "2025-09-16T16:15:38.223",
  "lastModified": "2025-09-16T16:15:38.223",
  "vulnStatus": "Rejected",
  "cveTags": [],
  "descriptions": [
    {
      "lang": "en",
      "value": "Rejected reason: ** REJECT ** DO NOT USE THIS CVE RECORD. ConsultIDs: none. Reason: This record was in a CNA pool that was not assigned to any issues during 2020. Notes: none."
    }
  ],
  "metrics": {},
  "references": []
}