{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2023-27559",
      "ASSIGNER": "psirt@us.ibm.com"
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-20"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "https://https://www.ibm.com/support/pages/node/6985667",
          "name": "https://https://www.ibm.com/support/pages/node/6985667",
          "refsource": "MISC",
          "tags": [

          ]
        },
        {
          "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/249196",
          "name": "https://exchange.xforce.ibmcloud.com/vulnerabilities/249196",
          "refsource": "MISC",
          "tags": [

          ]
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "IBM Db2 for Linux, UNIX and Windows (includes Db2 Connect Server) 10.5, 11.1, and 11.5 is vulnerable to a denial of service as the server may crash when using a specially crafted subquery.  IBM X-Force ID:  249196."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [

    ]
  },
  "impact": {
  },
  "publishedDate": "2023-04-26T20:15Z",
  "lastModifiedDate": "2023-04-26T20:15Z"
}