{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2025-3864",
      "ASSIGNER": "cvd@cert.pl"
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-772"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "https://cert.pl/en/posts/2025/05/CVE-2025-3864/",
          "name": "https://cert.pl/en/posts/2025/05/CVE-2025-3864/",
          "refsource": "",
          "tags": []
        },
        {
          "url": "https://github.com/benoitc/hackney/issues/717",
          "name": "https://github.com/benoitc/hackney/issues/717",
          "refsource": "",
          "tags": []
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "Hackney fails to properly release HTTP connections to the pool after handling 307 Temporary Redirect responses. Remote attackers can exploit this to exhaust connection pools, causing denial of service in applications using the library.\nFix for this issue has been included inÂ 1.24.0 release."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "impact": {},
  "publishedDate": "2025-05-28T12:15Z",
  "lastModifiedDate": "2025-05-28T12:15Z"
}