{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2022-49575",
      "ASSIGNER": "cve@kernel.org"
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "https://git.kernel.org/stable/c/404c53ccdebd11f96954f4070cffac8e0b4d5cb6",
          "name": "https://git.kernel.org/stable/c/404c53ccdebd11f96954f4070cffac8e0b4d5cb6",
          "refsource": "",
          "tags": []
        },
        {
          "url": "https://git.kernel.org/stable/c/492f3713b282c0e67e951cd804edd22eccc25412",
          "name": "https://git.kernel.org/stable/c/492f3713b282c0e67e951cd804edd22eccc25412",
          "refsource": "",
          "tags": []
        },
        {
          "url": "https://git.kernel.org/stable/c/7c6f2a86ca590d5187a073d987e9599985fb1c7c",
          "name": "https://git.kernel.org/stable/c/7c6f2a86ca590d5187a073d987e9599985fb1c7c",
          "refsource": "",
          "tags": []
        },
        {
          "url": "https://git.kernel.org/stable/c/a0f96c4f179cb3560078cefccef105e8f1701210",
          "name": "https://git.kernel.org/stable/c/a0f96c4f179cb3560078cefccef105e8f1701210",
          "refsource": "",
          "tags": []
        },
        {
          "url": "https://git.kernel.org/stable/c/cc133e4f4bc225079198192623945bb872c08143",
          "name": "https://git.kernel.org/stable/c/cc133e4f4bc225079198192623945bb872c08143",
          "refsource": "",
          "tags": []
        },
        {
          "url": "https://git.kernel.org/stable/c/f4b0295be9a3c4260de4585fac4062e602a88ac7",
          "name": "https://git.kernel.org/stable/c/f4b0295be9a3c4260de4585fac4062e602a88ac7",
          "refsource": "",
          "tags": []
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "In the Linux kernel, the following vulnerability has been resolved:\n\ntcp: Fix a data-race around sysctl_tcp_thin_linear_timeouts.\n\nWhile reading sysctl_tcp_thin_linear_timeouts, it can be changed\nconcurrently.  Thus, we need to add READ_ONCE() to its reader."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "impact": {},
  "publishedDate": "2025-02-26T07:01Z",
  "lastModifiedDate": "2025-02-26T07:01Z"
}