{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2023-6277",
      "ASSIGNER": "secalert@redhat.com"
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [

          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "https://access.redhat.com/security/cve/CVE-2023-6277",
          "name": "https://access.redhat.com/security/cve/CVE-2023-6277",
          "refsource": "",
          "tags": [

          ]
        },
        {
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2251311",
          "name": "RHBZ#2251311",
          "refsource": "",
          "tags": [

          ]
        },
        {
          "url": "https://gitlab.com/libtiff/libtiff/-/issues/614",
          "name": "https://gitlab.com/libtiff/libtiff/-/issues/614",
          "refsource": "",
          "tags": [

          ]
        },
        {
          "url": "https://gitlab.com/libtiff/libtiff/-/merge_requests/545",
          "name": "https://gitlab.com/libtiff/libtiff/-/merge_requests/545",
          "refsource": "",
          "tags": [

          ]
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "An out-of-memory flaw was found in libtiff. Passing a crafted tiff file to TIFFOpen() API may allow a remote attacker to cause a denial of service via a craft input with size smaller than 379 KB."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [

    ]
  },
  "impact": {
  },
  "publishedDate": "2023-11-24T19:15Z",
  "lastModifiedDate": "2023-11-24T19:15Z"
}