{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2024-24216",
      "ASSIGNER": "cve@mitre.org"
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [

          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "https://github.com/easysoft/zentaopms/issues/133",
          "name": "https://github.com/easysoft/zentaopms/issues/133",
          "refsource": "",
          "tags": [

          ]
        },
        {
          "url": "https://github.com/l3s10n/ZenTaoPMS_RCE",
          "name": "https://github.com/l3s10n/ZenTaoPMS_RCE",
          "refsource": "",
          "tags": [

          ]
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "Zentao v18.0 to v18.10 was discovered to contain a remote code execution (RCE) vulnerability via the checkConnection method of /app/zentao/module/repo/model.php."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [

    ]
  },
  "impact": {
  },
  "publishedDate": "2024-02-08T06:15Z",
  "lastModifiedDate": "2024-02-08T06:15Z"
}