{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2022-49455",
      "ASSIGNER": "cve@kernel.org"
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "https://git.kernel.org/stable/c/252768d32e92c1214aeebb5fec0844ca479bcf5c",
          "name": "https://git.kernel.org/stable/c/252768d32e92c1214aeebb5fec0844ca479bcf5c",
          "refsource": "",
          "tags": []
        },
        {
          "url": "https://git.kernel.org/stable/c/8fb674216835e1f0c143762696d645facebb4685",
          "name": "https://git.kernel.org/stable/c/8fb674216835e1f0c143762696d645facebb4685",
          "refsource": "",
          "tags": []
        },
        {
          "url": "https://git.kernel.org/stable/c/950cf957fe34d40d63dfa3bf3968210430b6491e",
          "name": "https://git.kernel.org/stable/c/950cf957fe34d40d63dfa3bf3968210430b6491e",
          "refsource": "",
          "tags": []
        },
        {
          "url": "https://git.kernel.org/stable/c/9e9087cf34ee69f4e95d146ac29385d6e367a97b",
          "name": "https://git.kernel.org/stable/c/9e9087cf34ee69f4e95d146ac29385d6e367a97b",
          "refsource": "",
          "tags": []
        },
        {
          "url": "https://git.kernel.org/stable/c/de65c32ace9aa70d51facc61ba986607075e3a25",
          "name": "https://git.kernel.org/stable/c/de65c32ace9aa70d51facc61ba986607075e3a25",
          "refsource": "",
          "tags": []
        },
        {
          "url": "https://git.kernel.org/stable/c/ee89d8dee55ab4b3b8ad8b70866b2841ba334767",
          "name": "https://git.kernel.org/stable/c/ee89d8dee55ab4b3b8ad8b70866b2841ba334767",
          "refsource": "",
          "tags": []
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "In the Linux kernel, the following vulnerability has been resolved:\n\nmisc: ocxl: fix possible double free in ocxl_file_register_afu\n\ninfo_release() will be called in device_unregister() when info->dev's\nreference count is 0. So there is no need to call ocxl_afu_put() and\nkfree() again.\n\nFix this by adding free_minor() and return to err_unregister error path."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "impact": {},
  "publishedDate": "2025-02-26T07:01Z",
  "lastModifiedDate": "2025-02-26T07:01Z"
}